{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from lccv import lccv\n",
    "from evalutils import *"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "openmlid = 41161\n",
    "X, y = get_dataset(openmlid)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Running without Timeout"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/felix/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)\n",
      "/home/felix/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)\n",
      "/home/felix/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)\n",
      "/home/felix/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)\n",
      "/home/felix/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)\n",
      "/home/felix/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)\n",
      "/home/felix/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)\n",
      "/home/felix/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)\n",
      "/home/felix/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "CPU times: user 7min 49s, sys: 12.4 s, total: 8min 2s\n",
      "Wall time: 2min 18s\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/felix/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "(0.012999999999999989,\n",
       " 0.012999999999999989,\n",
       " {64: {'n': 3,\n",
       "   'mean': 0.4622,\n",
       "   'std': 0.011332548992467089,\n",
       "   'conf': (0.44937624922940494, 0.47502375077059505)},\n",
       "  18000: {'n': 10,\n",
       "   'mean': 0.012999999999999989,\n",
       "   'std': 0.002073644135332758,\n",
       "   'conf': (0.011714765666153258, 0.01428523433384672)}},\n",
       " <lccv.EmpiricalLearningModel at 0x7f4df351b7d0>)"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "%%time\n",
    "lccv(sklearn.linear_model.LogisticRegression(), X, y)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Running With Timeout"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "CPU times: user 5.87 s, sys: 2.75 s, total: 8.62 s\n",
      "Wall time: 5.8 s\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/felix/devel/lccv/lccv/lccv.py:197: RuntimeWarning: invalid value encountered in sqrt\n",
      "  return -b/(2 * a) + np.sqrt(inner)\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "(0.4562,\n",
       " 0.4562,\n",
       " {64: {'n': 2,\n",
       "   'mean': 0.4562,\n",
       "   'std': 0.009200000000000041,\n",
       "   'conf': (0.4434496848159829, 0.4689503151840171)}},\n",
       " <lccv.EmpiricalLearningModel at 0x7f4df351b710>)"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "%%time\n",
    "lccv(sklearn.linear_model.LogisticRegression(), X, y, timeout=5)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Running with Threshold"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "All anchor evaluations enforced, setting r to 1.0\n",
      "True\n",
      "Running LCCV on (20000, 4296)-shaped data for learner DecisionTreeClassifier() with r = 1.0. Overview:\n",
      "\tmin_exp: 6\n",
      "\tmax_exp: 14.135709286104401\n",
      "Adding point at size 64\n",
      "std of [0.4857]: 0.0\n",
      "Adding point at size 64\n",
      "std of [0.4857 0.4098]: 0.037949999999999984\n",
      "Confidence bounds for performance interval at 64: (0.4036108425179703, 0.49188915748202977). Size: 0.08827831496405947\n",
      "Adding point at size 64\n",
      "std of [0.4857 0.4098 0.4102]: 0.03568569585826916\n",
      "Confidence bounds for performance interval at 64: (0.4013441737277038, 0.46912249293896285). Size: 0.06777831921125904\n",
      "Adding point at size 64\n",
      "std of [0.4857 0.4098 0.4102 0.4883]: 0.038511232127783165\n",
      "Confidence bounds for performance interval at 64: (0.4168273300781229, 0.4801726699218771). Size: 0.06334533984375423\n",
      "Adding point at size 64\n",
      "std of [0.4857 0.4098 0.4102 0.4883 0.3858]: 0.04260866578526014\n",
      "Confidence bounds for performance interval at 64: (0.4046170269054109, 0.4673029730945891). Size: 0.06268594618917822\n",
      "Adding point at size 64\n",
      "std of [0.4857 0.4098 0.4102 0.4883 0.3858 0.3875]: 0.04288447336222698\n",
      "Confidence bounds for performance interval at 64: (0.3990860371790679, 0.4566806294875989). Size: 0.057594592308531034\n",
      "Adding point at size 64\n",
      "std of [0.4857 0.4098 0.4102 0.4883 0.3858 0.3875 0.4438]: 0.04009206751404846\n",
      "Confidence bounds for performance interval at 64: (0.40523205545883756, 0.45508223025544825). Size: 0.04985017479661069\n",
      "Adding point at size 64\n",
      "std of [0.4857 0.4098 0.4102 0.4883 0.3858 0.3875 0.4438 0.4373]: 0.03757702090373849\n",
      "Confidence bounds for performance interval at 64: (0.40919732485671095, 0.452902675143289). Size: 0.04370535028657807\n",
      "Adding point at size 64\n",
      "std of [0.4857 0.4098 0.4102 0.4883 0.3858 0.3875 0.4438 0.4373 0.4154]: 0.035767721153900894\n",
      "Confidence bounds for performance interval at 64: (0.40970022248851684, 0.44892199973370533). Size: 0.039221777245188494\n",
      "Adding point at size 64\n",
      "std of [0.4857 0.4098 0.4102 0.4883 0.3858 0.3875 0.4438 0.4373 0.4154 0.3324]: 0.044683952376664254\n",
      "Confidence bounds for performance interval at 64: (0.3963777142073699, 0.4428622857926301). Size: 0.046484571585260204\n",
      "Adding point at size 128\n",
      "std of [0.4003]: 0.0\n",
      "Adding point at size 128\n",
      "std of [0.4003 0.3657]: 0.017299999999999982\n",
      "Confidence bounds for performance interval at 128: (0.36287859224139357, 0.40312140775860644). Size: 0.04024281551721287\n",
      "Adding point at size 128\n",
      "std of [0.4003 0.3657 0.3998]: 0.01619403182245442\n",
      "Confidence bounds for performance interval at 128: (0.3732212294340722, 0.4039787705659278). Size: 0.03075754113185558\n",
      "Adding point at size 128\n",
      "std of [0.4003 0.3657 0.3998 0.3978]: 0.014579266099498972\n",
      "Confidence bounds for performance interval at 128: (0.37890962063897426, 0.4028903793610258). Size: 0.02398075872205152\n",
      "Adding point at size 128\n",
      "std of [0.4003 0.3657 0.3998 0.3978 0.36  ]: 0.017967014220509774\n",
      "Confidence bounds for performance interval at 128: (0.37150344808678926, 0.39793655191321076). Size: 0.0264331038264215\n",
      "Adding point at size 128\n",
      "std of [0.4003 0.3657 0.3998 0.3978 0.36   0.3567]: 0.01944365792060058\n",
      "Confidence bounds for performance interval at 128: (0.36699341491074594, 0.39310658508925406). Size: 0.026113170178508116\n",
      "Adding point at size 128\n",
      "std of [0.4003 0.3657 0.3998 0.3978 0.36   0.3567 0.4365]: 0.02672534530427349\n",
      "Confidence bounds for performance interval at 128: (0.37149923917857164, 0.40472933224999985). Size: 0.03323009307142821\n",
      "Adding point at size 128\n",
      "std of [0.4003 0.3657 0.3998 0.3978 0.36   0.3567 0.4365 0.4331]: 0.029091362012631863\n",
      "Confidence bounds for performance interval at 128: (0.3768196052800752, 0.41065539471992485). Size: 0.03383578943984966\n",
      "Adding point at size 128\n",
      "std of [0.4003 0.3657 0.3998 0.3978 0.36   0.3567 0.4365 0.4331 0.41  ]: 0.027899705737640206\n",
      "Confidence bounds for performance interval at 128: (0.38024746705329904, 0.4108414218355899). Size: 0.030593954782290878\n",
      "Adding point at size 128\n",
      "std of [0.4003 0.3657 0.3998 0.3978 0.36   0.3567 0.4365 0.4331 0.41   0.3815]: 0.02680123877734013\n",
      "Confidence bounds for performance interval at 128: (0.3801993788568987, 0.4080806211431014). Size: 0.0278812422862027\n",
      "Adding point at size 256\n",
      "std of [0.3368]: 0.0\n",
      "Adding point at size 256\n",
      "std of [0.3368 0.3307]: 0.003049999999999997\n",
      "Confidence bounds for performance interval at 256: (0.3302025841812861, 0.33729741581871386). Size: 0.007094831637427745\n",
      "Adding point at size 256\n",
      "std of [0.3368 0.3307 0.3698]: 0.017175628728585822\n",
      "Confidence bounds for performance interval at 256: (0.32945571603754503, 0.3620776172957884). Size: 0.03262190125824338\n",
      "Adding point at size 256\n",
      "std of [0.3368 0.3307 0.3698 0.3324]: 0.015960948436731452\n",
      "Confidence bounds for performance interval at 256: (0.32929828803712846, 0.3555517119628716). Size: 0.026253423925743147\n",
      "Adding point at size 256\n",
      "std of [0.3368 0.3307 0.3698 0.3324 0.3251]: 0.015869039038328706\n",
      "Confidence bounds for performance interval at 256: (0.3272867205285883, 0.35063327947141176). Size: 0.023346558942823448\n",
      "Adding point at size 256\n",
      "std of [0.3368 0.3307 0.3698 0.3324 0.3251 0.3094]: 0.01819932843693843\n",
      "Confidence bounds for performance interval at 256: (0.32181232629471396, 0.34625434037195274). Size: 0.024442014077238783\n",
      "Adding point at size 256\n",
      "std of [0.3368 0.3307 0.3698 0.3324 0.3251 0.3094 0.3798]: 0.02324605737912281\n",
      "Confidence bounds for performance interval at 256: (0.32611944223678446, 0.3550234149060727). Size: 0.028903972669288236\n",
      "Adding point at size 256\n",
      "std of [0.3368 0.3307 0.3698 0.3324 0.3251 0.3094 0.3798 0.3578]: 0.022478809465805803\n",
      "Confidence bounds for performance interval at 256: (0.3296525927401878, 0.3557974072598122). Size: 0.02614481451962436\n",
      "Adding point at size 256\n",
      "std of [0.3368 0.3307 0.3698 0.3324 0.3251 0.3094 0.3798 0.3578 0.3787]: 0.02402030519640406\n",
      "Confidence bounds for performance interval at 256: (0.33355226018129336, 0.35989218426315106). Size: 0.026339924081857702\n",
      "Adding point at size 256\n",
      "std of [0.3368 0.3307 0.3698 0.3324 0.3251 0.3094 0.3798 0.3578 0.3787 0.3557]: 0.022946276386376956\n",
      "Confidence bounds for performance interval at 256: (0.335684531329879, 0.35955546867012095). Size: 0.023870937340241927\n",
      "Adding point at size 512\n",
      "std of [0.3092]: 0.0\n",
      "Adding point at size 512\n",
      "std of [0.3092 0.3093]: 4.999999999999449e-05\n",
      "Confidence bounds for performance interval at 512: (0.3091918456423162, 0.30930815435768383). Size: 0.0001163087153676079\n",
      "Switching to hold-out mode.\n",
      "Adding point at size 512\n",
      "std of [0.3092 0.3093 0.3588]: 0.023358129681595268\n",
      "Confidence bounds for performance interval at 512: (0.303584462681841, 0.3479488706514923). Size: 0.0443644079696513\n",
      "Adding point at size 512\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/magics/execution.py\", line 1307, in time\n",
      "    out = eval(code, glob, local_ns)\n",
      "  File \"<timed eval>\", line 1, in <module>\n",
      "  File \"/home/felix/devel/lccv/lccv/lccv.py\", line 279, in lccv\n",
      "    elm.compute_and_add_sample(size, seed, (deadline - time.time()) * 1000 if deadline is not None else None)\n",
      "  File \"/home/felix/devel/lccv/lccv/lccv.py\", line 83, in compute_and_add_sample\n",
      "    error_rate = evaluate(sklearn.base.clone(self.learner), self.X, self.y, size, seed, timeout / 1000 if timeout is not None else None)\n",
      "  File \"/home/felix/devel/lccv/lccv/evalutils.py\", line 48, in evaluate\n",
      "    X_test = X[mask_test][:10000]\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "KeyboardInterrupt\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/magics/execution.py\", line 1307, in time\n",
      "    out = eval(code, glob, local_ns)\n",
      "  File \"<timed eval>\", line 1, in <module>\n",
      "  File \"/home/felix/devel/lccv/lccv/lccv.py\", line 279, in lccv\n",
      "    elm.compute_and_add_sample(size, seed, (deadline - time.time()) * 1000 if deadline is not None else None)\n",
      "  File \"/home/felix/devel/lccv/lccv/lccv.py\", line 83, in compute_and_add_sample\n",
      "    error_rate = evaluate(sklearn.base.clone(self.learner), self.X, self.y, size, seed, timeout / 1000 if timeout is not None else None)\n",
      "  File \"/home/felix/devel/lccv/lccv/evalutils.py\", line 48, in evaluate\n",
      "    X_test = X[mask_test][:10000]\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-3-e51ac56f89d9>\", line 1, in <module>\n",
      "    get_ipython().run_cell_magic('time', '', 'lccv(sklearn.tree.DecisionTreeClassifier(), X, y, r = 1.0, enforce_all_anchor_evaluations=True, timeout=500, verbose=True)\\n')\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2371, in run_cell_magic\n",
      "    result = fn(*args, **kwargs)\n",
      "  File \"<decorator-gen-61>\", line 2, in time\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/magic.py\", line 187, in <lambda>\n",
      "    call = lambda f, *a, **k: f(*a, **k)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/magics/execution.py\", line 1309, in time\n",
      "    self.shell.showtraceback()\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "KeyboardInterrupt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/magics/execution.py\", line 1307, in time\n",
      "    out = eval(code, glob, local_ns)\n",
      "  File \"<timed eval>\", line 1, in <module>\n",
      "  File \"/home/felix/devel/lccv/lccv/lccv.py\", line 279, in lccv\n",
      "    elm.compute_and_add_sample(size, seed, (deadline - time.time()) * 1000 if deadline is not None else None)\n",
      "  File \"/home/felix/devel/lccv/lccv/lccv.py\", line 83, in compute_and_add_sample\n",
      "    error_rate = evaluate(sklearn.base.clone(self.learner), self.X, self.y, size, seed, timeout / 1000 if timeout is not None else None)\n",
      "  File \"/home/felix/devel/lccv/lccv/evalutils.py\", line 48, in evaluate\n",
      "    X_test = X[mask_test][:10000]\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-3-e51ac56f89d9>\", line 1, in <module>\n",
      "    get_ipython().run_cell_magic('time', '', 'lccv(sklearn.tree.DecisionTreeClassifier(), X, y, r = 1.0, enforce_all_anchor_evaluations=True, timeout=500, verbose=True)\\n')\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2371, in run_cell_magic\n",
      "    result = fn(*args, **kwargs)\n",
      "  File \"<decorator-gen-61>\", line 2, in time\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/magic.py\", line 187, in <lambda>\n",
      "    call = lambda f, *a, **k: f(*a, **k)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/magics/execution.py\", line 1309, in time\n",
      "    self.shell.showtraceback()\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3263, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3360, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/inspect.py\", line 739, in getmodule\n",
      "    f = getabsfile(module)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/inspect.py\", line 708, in getabsfile\n",
      "    _filename = getsourcefile(object) or getfile(object)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/inspect.py\", line 693, in getsourcefile\n",
      "    if os.path.exists(filename):\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/genericpath.py\", line 19, in exists\n",
      "    os.stat(path)\n",
      "KeyboardInterrupt\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/magics/execution.py\", line 1307, in time\n",
      "    out = eval(code, glob, local_ns)\n",
      "  File \"<timed eval>\", line 1, in <module>\n",
      "  File \"/home/felix/devel/lccv/lccv/lccv.py\", line 279, in lccv\n",
      "    elm.compute_and_add_sample(size, seed, (deadline - time.time()) * 1000 if deadline is not None else None)\n",
      "  File \"/home/felix/devel/lccv/lccv/lccv.py\", line 83, in compute_and_add_sample\n",
      "    error_rate = evaluate(sklearn.base.clone(self.learner), self.X, self.y, size, seed, timeout / 1000 if timeout is not None else None)\n",
      "  File \"/home/felix/devel/lccv/lccv/evalutils.py\", line 48, in evaluate\n",
      "    X_test = X[mask_test][:10000]\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-3-e51ac56f89d9>\", line 1, in <module>\n",
      "    get_ipython().run_cell_magic('time', '', 'lccv(sklearn.tree.DecisionTreeClassifier(), X, y, r = 1.0, enforce_all_anchor_evaluations=True, timeout=500, verbose=True)\\n')\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2371, in run_cell_magic\n",
      "    result = fn(*args, **kwargs)\n",
      "  File \"<decorator-gen-61>\", line 2, in time\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/magic.py\", line 187, in <lambda>\n",
      "    call = lambda f, *a, **k: f(*a, **k)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/magics/execution.py\", line 1309, in time\n",
      "    self.shell.showtraceback()\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3263, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3360, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2895, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3072, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3282, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1211, in structured_traceback\n",
      "    chained_exceptions_tb_offset)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1169, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 316, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 350, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/home/felix/anaconda3/lib/python3.7/inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "KeyboardInterrupt\n"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "lccv(sklearn.tree.DecisionTreeClassifier(), X, y, r = 1.0, enforce_all_anchor_evaluations=True, timeout=500, verbose=True)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Making Recommendations on whether or not collect more data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Conducting recommendation analysis now only for DecisionTreeClassifier\n",
      "\n",
      "----------------- 1 -----------------\n",
      "Doing this on higgs. Here we *will* recognize saturation and the recommendation for more data will be good.\n",
      "Conducting validation on 44122/88244 instances.\n",
      "Score at half size (44122): 0.37606000000000006\n",
      "Estimated score on full data (88244 instances): 0.36826329002668334\n",
      "This would be an improvement of: 0.007796709973316718\n",
      "Recommending to double the number of instances: False\n",
      "Now computing the TRUE performance at the target.\n",
      "True performance at target: 0.3715553289138195\n",
      "The true improvement is: 0.004504671086180578\n",
      "Recommendation was good\n",
      "\n",
      "----------------- 2 -----------------\n",
      "Doing this on Madelon will be overly optimistic, but the recommendation for more data would still be correct.\n",
      "Conducting validation on 1170/2340 instances.\n",
      "Score at half size (1170): 0.3336363636363637\n",
      "Estimated score on full data (2340 instances): 0.2976369490387043\n",
      "This would be an improvement of: 0.035999414597659374\n",
      "Recommending to double the number of instances: True\n",
      "Now computing the TRUE performance at the target.\n",
      "True performance at target: 0.2353846153846154\n",
      "The true improvement is: 0.09825174825174829\n",
      "Recommendation was good\n",
      "\n",
      "----------------- 3 -----------------\n",
      "We are also good in recognizing it on wine-quality-white!\n",
      "Conducting validation on 2204/4408 instances.\n",
      "Score at half size (2204): 0.46726057906458796\n",
      "Estimated score on full data (4408 instances): 0.4512591758076496\n",
      "This would be an improvement of: 0.01600140325693833\n",
      "Recommending to double the number of instances: True\n",
      "Now computing the TRUE performance at the target.\n",
      "True performance at target: 0.3714285714285714\n",
      "The true improvement is: 0.09583200763601657\n",
      "Recommendation was good\n",
      "\n",
      "----------------- 4 -----------------\n",
      "On amazon, it works also well!\n",
      "Conducting validation on 675/1350 instances.\n",
      "Score at half size (675): 0.6408484848484849\n",
      "Estimated score on full data (1350 instances): 0.5582903918255298\n",
      "This would be an improvement of: 0.08255809302295514\n",
      "Recommending to double the number of instances: True\n",
      "Now computing the TRUE performance at the target.\n",
      "True performance at target: 0.5706666666666667\n",
      "The true improvement is: 0.07018181818181823\n",
      "Recommendation was good\n"
     ]
    }
   ],
   "source": [
    "from lccv import lccv\n",
    "from evalutils import *\n",
    "\n",
    "def check_possible_improvement(learner, X, y):\n",
    "    n = X.shape[0]\n",
    "    target = int(0.9 * n)\n",
    "    half = int(target/2)\n",
    "    print(\"Conducting validation on \" + str(half) + \"/\" + str(target) + \" instances.\")\n",
    "    validation_score, mean_estimates, estimates, elm = lccv(learner(), X, y, r = 1.0, enforce_all_anchor_evaluations=True, target = half, timeout=500, verbose=False)\n",
    "    \n",
    "    prediction_on_full = elm.get_ipl_estimate_at_target(target)\n",
    "    expected_improvement = validation_score - prediction_on_full\n",
    "    print(\"Score at half size (\" + str(half) + \"):\", validation_score)\n",
    "    print(\"Estimated score on full data (\" + str(target) + \" instances):\", prediction_on_full)\n",
    "    print(\"This would be an improvement of:\", expected_improvement)\n",
    "    recommendation = expected_improvement >= 0.01\n",
    "    print(\"Recommending to double the number of instances:\", recommendation)\n",
    "    \n",
    "    # now computing the true performance there\n",
    "    print(\"Now computing the TRUE performance at the target.\")\n",
    "    for seed in range(10):\n",
    "        elm.compute_and_add_sample(target, seed=seed)\n",
    "    true_performance_at_target = np.mean(elm.get_values_at_anchor(target))\n",
    "    true_improvement_at_target = validation_score - true_performance_at_target\n",
    "    print(\"True performance at target:\", true_performance_at_target)\n",
    "    print(\"The true improvement is:\", true_improvement_at_target)\n",
    "    print(\"Recommendation was \" + (\"good\" if (recommendation and true_improvement_at_target >= 0.01 or not recommendation and true_improvement_at_target < 0.01) else \"bad\"))\n",
    "\n",
    "    \n",
    "learner = sklearn.tree.DecisionTreeClassifier\n",
    "print(\"Conducting recommendation analysis now only for \" + learner.__name__)\n",
    "\n",
    "print(\"\\n----------------- 1 -----------------\")\n",
    "print(\"Doing this on higgs. Here we *will* recognize saturation and the recommendation for more data will be good.\")\n",
    "openmlid = 23512\n",
    "X, y = get_dataset(openmlid)\n",
    "check_possible_improvement(learner, X, y)\n",
    "\n",
    "print(\"\\n----------------- 2 -----------------\")\n",
    "print(\"Doing this on Madelon will be overly optimistic, but the recommendation for more data would still be correct.\")\n",
    "openmlid = 1485\n",
    "X, y = get_dataset(openmlid)\n",
    "check_possible_improvement(learner, X, y)\n",
    "\n",
    "print(\"\\n----------------- 3 -----------------\")\n",
    "print(\"We are also good in recognizing it on wine-quality-white!\")\n",
    "openmlid = 40498\n",
    "X, y = get_dataset(openmlid)\n",
    "check_possible_improvement(learner, X, y)\n",
    "\n",
    "print(\"\\n----------------- 4 -----------------\")\n",
    "print(\"On amazon, it works also well!\")\n",
    "openmlid = 1457\n",
    "X, y = get_dataset(openmlid)\n",
    "check_possible_improvement(learner, X, y)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
